version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - 8077:80
    environment:
      LOCATION: "/ducks"
    volumes:
      - ./ducks:/ducks
      - .:/app
    command: ["run", "uvicorn", "api.main:app", "--reload", "--host", "0.0.0.0", "--port", "80"]
