name: Build & Deploy

on:
  workflow_call:
    inputs:
      sha-tag:
        description: "A short-form SHA tag for the commit that triggered this workflow"
        required: true
        type: string

jobs:
  build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=ghcr.io/python-discord/quackstack:main
          cache-to: type=inline
          tags: |
            ghcr.io/python-discord/quackstack:main
            ghcr.io/python-discord/quackstack:${{ inputs.sha-tag }}

  deploy:
    name: Deploy to Kubernetes
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout infra repo for deployment manifest
        uses: actions/checkout@v4
        with:
          repository: python-discord/infra
          path: infra

      - uses: azure/setup-kubectl@v4

      - name: Authenticate with Kubernetes
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          namespace: apis
          manifests: |
            infra/kubernetes/namespaces/apis/quackstack/deployment.yaml
          images: 'ghcr.io/python-discord/quackstack:${{ inputs.sha-tag }}'
